---
title: "Midterm Project"
author: "Yijing Tao yt2785"
date: '2022-03-16'
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(ISLR)
library(glmnet)
library(caret)
library(corrplot)
library(plotmo)
library(mgcv)
library(earth)
library(splines)
library(mgcv)
library(pdp)
library(earth)
library(tidyverse)
library(ggplot2)
library(lasso2)
library(vip)
library(summarytools)
library(ISLR)
library(caret)
library(vip)
library(pdp)
library(lime)
library(mlbench)
library(ISLR)
library(caret)
library(e1071)
library(kernlab)
library(factoextra)
library(gridExtra)
library(corrplot)
library(RColorBrewer) 
library(gplots)
library(jpeg)
library(klaR)
library(pROC)
library(rpart.plot)
library(patchwork)
```

## import data set (70% to train data while 30% to test data)
```{r}
dat_df_nores = read_csv("./data.csv") %>% 
  dplyr::select(-diagnosis)
dat_df_res = read_csv("./data.csv") %>% 
  dplyr::select(diagnosis)
dat_df_wait = cbind(dat_df_nores, dat_df_res) 
dat_df <- dat_df_wait[,2:32]
rownames(dat_df) = dat_df_wait[,1]

dat_df2 <- model.matrix(diagnosis ~ ., dat_df)[ ,-1]
#assign 70% to the training set and the rest 30% to the test set 
set.seed(2022)
trainRows <- createDataPartition(dat_df$diagnosis, p = .7, list = F)

train <- dat_df[trainRows,]
x1 <- dat_df2[trainRows,]
train$diagnosis[which(train$diagnosis =='M')] <- 'neg'
train$diagnosis[which(train$diagnosis =='B')] <- 'pos'
train <- train %>% 
  mutate(diagnosis = as.factor(diagnosis))
y1 <- train$diagnosis

# matrix of predictors (glmnet uses input matrix)
test <- dat_df[-trainRows,]
x2 <- dat_df2[-trainRows,]
test$diagnosis[which(test$diagnosis =='M')] <- 'neg'
test$diagnosis[which(test$diagnosis =='B')] <- 'pos'
test <- test %>% 
  mutate(diagnosis = as.factor(diagnosis))
y2 <- test$diagnosis

ctrl <- trainControl(method = "repeatedcv",
                     summaryFunction = twoClassSummary,
                     classProbs = TRUE)
```

## visualization
```{r}
dfSummary(dat_df[,-1])
```

```{r, fig.height = 4}
train_radius <- train %>% 
  dplyr::select(radius_mean,
                radius_se,
                radius_worst,diagnosis)
train_texture <- train %>% 
  dplyr::select(texture_mean,
                texture_se,
                texture_worst,diagnosis)
train_perimeter <- train %>% 
  dplyr::select(perimeter_mean,
                perimeter_se,
                perimeter_worst,diagnosis)
train_area <- train %>% 
  dplyr::select(area_mean,
                area_se,
                area_worst,diagnosis)
train_smoothness <- train %>% 
  dplyr::select(smoothness_mean,
                smoothness_se,
                smoothness_worst,diagnosis)
train_compactness <- train %>% 
  dplyr::select(compactness_mean,
                compactness_se,
                compactness_worst,diagnosis)
train_concavity <- train %>% 
  dplyr::select(concavity_mean,
                concavity_se,
                concavity_worst,diagnosis)
train_concave_points <- train %>% 
  dplyr::select(concave_points_mean,
                concave_points_se,
                concave_points_worst,diagnosis)
train_symmetry <- train %>% 
  dplyr::select(symmetry_mean,
                symmetry_se,
                symmetry_worst,diagnosis)
train_fractal_dimension <- train %>% 
  dplyr::select(fractal_dimension_mean,
                fractal_dimension_se,
                fractal_dimension_worst,diagnosis)

partimat(diagnosis ~ ., 
         data = train_radius, method = "lda")
partimat(diagnosis ~ ., 
         data = train_texture, method = "lda")
partimat(diagnosis ~ ., 
         data = train_perimeter, method = "lda")
partimat(diagnosis ~ ., 
         data = train_area, method = "lda")
partimat(diagnosis ~ ., 
         data = train_smoothness, method = "lda")
partimat(diagnosis ~ ., 
         data = train_compactness, method = "lda")
partimat(diagnosis ~ ., 
         data = train_concavity, method = "lda")
partimat(diagnosis ~ ., 
         data = train_concave_points, method = "lda")
partimat(diagnosis ~ ., 
         data = train_symmetry, method = "lda")
partimat(diagnosis ~ ., 
         data = train_fractal_dimension, method = "lda")
```

## KNN model
```{r}
kGrid <- expand.grid(k = seq(from = 1, to = 30, by = 1))
set.seed(2022)
knn.fit <- train(diagnosis ~., 
                data = train, 
                method = "knn",
                metric = "ROC",
                trControl = ctrl,
                tuneGrid = kGrid)
```

```{r eval=FALSE, include=FALSE}
save(knn.fit, file = "./result/model.knn.RData")

load("./result/model.knn.RData")
```

```{r}
ggplot(knn.fit)
knn.fit$bestTune

train.pred.prob.knn <- predict(knn.fit, newdata = train)
knn_matrix_train <- confusionMatrix(data = train.pred.prob.knn,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_knn = as.data.frame(1-knn_matrix_train$overall[1])[1,]
train_err_rate_knn

test.pred.prob.knn <- predict(knn.fit, newdata = test)
knn_matrix <- confusionMatrix(data = test.pred.prob.knn,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_knn = as.data.frame(1-knn_matrix$overall[1])[1,]
test_err_rate_knn
```

## glm model
```{r}
contrasts(train$diagnosis)
set.seed(2022)
model.glm <- train(x = train[,1:30],
                   y = train$diagnosis,
                   method = "glm",
                   metric = "ROC",
                   trControl = ctrl)

```

```{r eval=FALSE, include=FALSE}
save(model.glm, file = "./result/model.glm.RData")

load("./result/model.glm.RData")
```

```{r}
train.pred.prob.glm <- predict(model.glm, newdata = train)
glm_matrix_train <- confusionMatrix(data = train.pred.prob.glm,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_glm = as.data.frame(1-glm_matrix_train$overall[1])[1,]
train_err_rate_glm

test.pred.prob.glm <- predict(model.glm, newdata = test)
glm_matrix <- confusionMatrix(data = test.pred.prob.glm,
                reference = test$diagnosis,
                positive = "pos")
test_err_rate_glm = as.data.frame(1-glm_matrix$overall[1])[1,]
test_err_rate_glm
```

## Penalized logistic regression
```{r}
glmnGrid <- expand.grid(.alpha = seq(0, 1, length = 21),
                        .lambda = exp(seq(-8, -1, length = 50)))
set.seed(2022)
model.glmn <- train(x = train[,1:30],
                    y = train$diagnosis,
                    method = "glmnet",
                    tuneGrid = glmnGrid,
                    metric = "ROC",
                    trControl = ctrl)
```

```{r eval=FALSE, include=FALSE}
save(model.glmn, file = "./result/model.glmn.RData")

load("./result/model.glmn.RData")
```

```{r}
model.glmn$bestTune
log(model.glmn$bestTune$lambda)

myCol<- rainbow(25)
myPar <- list(superpose.symbol = list(col = myCol),
              superpose.line = list(col = myCol))

plot(model.glmn, par.settings = myPar, xTrans = function(x) log(x))

train.pred.prob.glmn <- predict(model.glmn, newdata = train)
glmn_matrix_train <- confusionMatrix(data = train.pred.prob.glmn,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_glmn = as.data.frame(1-glmn_matrix_train$overall[1])[1,]
train_err_rate_glmn

test.pred.prob.glmn <- predict(model.glmn, newdata = test)
glmn_matrix <- confusionMatrix(data = test.pred.prob.glmn,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_glmn = as.data.frame(1-glmn_matrix$overall[1])[1,]
test_err_rate_glmn
```

## GAM

```{r}
set.seed(2022)
model.gam <- train(x = train[,1:30],
                   y = train$diagnosis,
                   method = "gam",
                   metric = "ROC",
                   trControl = ctrl)
```

```{r eval=FALSE, include=FALSE}
save(model.gam, file = "./result/model.gam.RData")

load("./result/model.gam.RData")
```

```{r}
model.gam$finalModel

train.pred.prob.gam<- predict(model.gam, newdata = train)
gam_matrix_train <- confusionMatrix(data = train.pred.prob.gam,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_gam = as.data.frame(1-gam_matrix_train$overall[1])[1,]
train_err_rate_gam

test.pred.prob.gam<- predict(model.gam, newdata = test)
gam_matrix <- confusionMatrix(data = test.pred.prob.gam,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_gam = as.data.frame(1-gam_matrix$overall[1])[1,]
test_err_rate_gam
```

## MARS

```{r}
set.seed(2022)
model.mars <- train(x = train[,1:30],
                    y = train$diagnosis,
                    method = "earth",
                    tuneGrid = expand.grid(degree = 1:4, 
                                           nprune = 1:30),
                    metric = "ROC",
                    trControl = ctrl)
```

```{r eval=FALSE, include=FALSE}
save(model.mars, file = "./result/model.mars.RData")

load("./result/model.mars.RData")
```

```{r}
model.mars$bestTune
train.pred.prob.mars <- predict(model.mars, newdata = train)
mars_matrix_train <- confusionMatrix(data = train.pred.prob.mars,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_mars = as.data.frame(1-mars_matrix_train$overall[1])[1,]
train_err_rate_mars

test.pred.prob.mars <- predict(model.mars, newdata = test)
mars_matrix <- confusionMatrix(data = test.pred.prob.mars,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_mars = as.data.frame(1-mars_matrix$overall[1])[1,]
test_err_rate_mars
```

## LDA
```{r}
set.seed(2022)
model.lda <- train(x = train[,1:30],
                   y = train$diagnosis,
                   method = "lda",
                   metric = "ROC",
                   trControl = ctrl)
```

```{r eval=FALSE, include=FALSE}
save(model.lda, file = "./result/model.lda.RData")

load("./result/model.lda.RData")
```

```{r}
model.lda$bestTune

train.pred.prob.lda <- predict(model.lda, newdata = train)
lda_matrix_train <- confusionMatrix(data = train.pred.prob.lda,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_lda = as.data.frame(1-lda_matrix_train$overall[1])[1,]
train_err_rate_lda

test.pred.prob.lda <- predict(model.lda, newdata = test)
lda_matrix <- confusionMatrix(data = test.pred.prob.lda,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_lda = as.data.frame(1-lda_matrix$overall[1])[1,]
test_err_rate_lda
```

## QDA
```{r}
set.seed(2022)
model.qda <- train(x = train[,1:30],
                   y = train$diagnosis,
                   method = "qda",
                   metric = "ROC",
                   trControl = ctrl)
```

```{r eval=FALSE, include=FALSE}
save(model.qda, file = "./result/model.qda.RData")

load("./result/model.qda.RData")
```

```{r}
model.qda$bestTune

train.pred.prob.qda <- predict(model.qda, newdata = train)
qda_matrix_train <- confusionMatrix(data = train.pred.prob.qda,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_qda = as.data.frame(1-qda_matrix_train$overall[1])[1,]
train_err_rate_qda

test.pred.prob.qda <- predict(model.qda, newdata = test)
qda_matrix <- confusionMatrix(data = test.pred.prob.qda,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_qda = as.data.frame(1-qda_matrix$overall[1])[1,]
test_err_rate_qda
```

## Naive Bayes (NB)
```{r, warning=FALSE}
nbGrid <- expand.grid(usekernel = c(FALSE,TRUE),
                      fL = 1, 
                      adjust = seq(.2, 3, by = .2))

set.seed(2022)
model.nb <- train(x = train[,1:30],
                  y = train$diagnosis,
                  method = "nb",
                  tuneGrid = nbGrid,
                  metric = "ROC",
                  trControl = ctrl)
```

```{r eval=FALSE, include=FALSE}
save(model.nb, file = "./result/model.nb.RData")

load("./result/model.nb.RData")
```

```{r warning=FALSE}
model.nb$bestTune

plot(model.nb)
train.pred.prob.nb <- predict(model.nb, newdata = train)
nb_matrix_train <- confusionMatrix(data = train.pred.prob.nb,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_nb = as.data.frame(1-nb_matrix_train$overall[1])[1,]
train_err_rate_nb

test.pred.prob.nb <- predict(model.nb, newdata = test)
nb_matrix <- confusionMatrix(data = test.pred.prob.nb,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_nb = as.data.frame(1-nb_matrix$overall[1])[1,]
test_err_rate_nb 
```

## Classification tree
```{r}
set.seed(2022)
rpart.fit <- train(diagnosis ~ . , 
                   train, 
                   method = "rpart",
                   tuneGrid = data.frame(cp = exp(seq(-6,-3, len = 50))),
                   trControl = ctrl,
                   metric = "ROC")
```

```{r eval=FALSE, include=FALSE}
save(rpart.fit, file = "./result/model.rpart.RData")

load("./result/model.rpart.RData")
```

```{r}
log(rpart.fit$bestTune)
ggplot(rpart.fit, highlight = TRUE)

rpart.fit$finalModel
rpart.plot(rpart.fit$finalModel)

train.pred.prob.rpart <- predict(rpart.fit, newdata = train)
rpart_matrix_train <- confusionMatrix(data = train.pred.prob.rpart,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_rpart = as.data.frame(1-rpart_matrix_train$overall[1])[1,]
train_err_rate_rpart 

test.pred.prob.rpart <- predict(rpart.fit, newdata = test)
rpart_matrix <- confusionMatrix(data = test.pred.prob.rpart,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_rpart = as.data.frame(1-rpart_matrix$overall[1])[1,]
test_err_rate_rpart 
```

### CIT

```{r}
set.seed(2022)
ctree.fit <- train(diagnosis ~ . , 
                   train, 
                   method = "ctree",
                   tuneGrid = data.frame(mincriterion = 1-exp(seq(-2, -1, length = 50))),
                   metric = "ROC",
                   trControl = ctrl)
```

```{r eval=FALSE, include=FALSE}
save(ctree.fit, file = "./result/model.ctree.RData")

load("./result/model.ctree.RData")
```

```{r, fig.width=15, fig.height=6}
ctree.fit$bestTune
log(1-ctree.fit$bestTune)

ggplot(ctree.fit, highlight = TRUE)
plot(ctree.fit$finalModel)

train.pred.prob.ctree <- predict(ctree.fit, newdata = train)
ctree_matrix_train <- confusionMatrix(data = train.pred.prob.ctree,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_ctree = as.data.frame(1-ctree_matrix_train$overall[1])[1,]
train_err_rate_ctree

test.pred.prob.ctree <- predict(ctree.fit, newdata = test)
ctree_matrix <- confusionMatrix(data = test.pred.prob.ctree,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_ctree = as.data.frame(1-ctree_matrix$overall[1])[1,]
test_err_rate_ctree
```

### Random forests

```{r}
rf.grid <- expand.grid(mtry = 1:8,
                       splitrule = "gini",
                       min.node.size = seq(from = 2, to = 10, by = 2))
set.seed(2022)
rf.fit <- train(diagnosis ~ . , 
                train, 
                method = "ranger",
                tuneGrid = rf.grid,
                metric = "ROC",
                trControl = ctrl)
```

```{r eval=FALSE, include=FALSE}
save(rf.fit, file = "./result/model.rf.RData")

load("./result/model.rf.RData")
```

```{r}
rf.fit$bestTune

ggplot(rf.fit, highlight = TRUE)
#plot(rf.fit$finalModel)

train.pred.prob.rf <- predict(rf.fit, newdata = train)
rf_matrix_train <- confusionMatrix(data = train.pred.prob.rf,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_rf = as.data.frame(1-rf_matrix_train$overall[1])[1,]
train_err_rate_rf

test.pred.prob.rf <- predict(rf.fit, newdata = test)
rf_matrix <- confusionMatrix(data = test.pred.prob.rf,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_rf = as.data.frame(1-rf_matrix$overall[1])[1,]
test_err_rate_rf
```

### AdaBoost

```{r}
gbmA.grid <- expand.grid(n.trees = c(4000,5000, 6000,7000),
                         interaction.depth = 2:8,
                         shrinkage = c(0.0005,0.001,0.002),
                         n.minobsinnode = 1)
set.seed(2022)
gbmA.fit <- train(diagnosis ~ . , 
                  train, 
                  tuneGrid = gbmA.grid,
                  trControl = ctrl,
                  method = "gbm",
                  distribution = "adaboost",
                  metric = "ROC",
                  verbose = FALSE)
```


```{r eval=FALSE, include=FALSE}
save(gbmA.fit, file = "./result/model.gbmA.RData")

load("./result/model.gbmA.RData")
```

```{r}
ggplot(gbmA.fit, highlight = TRUE)

train.pred.prob.gbmA <- predict(gbmA.fit, newdata = train)
gbmA_matrix_train <- confusionMatrix(data = train.pred.prob.gbmA,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_gbmA = as.data.frame(1-gbmA_matrix_train$overall[1])[1,]
train_err_rate_gbmA

test.pred.prob.gbmA <- predict(gbmA.fit, newdata = test)
gbmA_matrix <- confusionMatrix(data = test.pred.prob.gbmA,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_gbmA = as.data.frame(1-gbmA_matrix$overall[1])[1,]
test_err_rate_gbmA
```

## linear svm
```{r}
# kernlab
set.seed(2022)
svml.fit <- train(diagnosis ~ . , 
                  data = train, 
                  method = "svmLinear",
                  # preProcess = c("center", "scale"),
                  tuneGrid = data.frame(C = exp(seq(-5,2,len=50))),
                  trControl = ctrl)

plot(svml.fit, highlight = TRUE, xTrans = log)

log(svml.fit$bestTune)

# e1071
set.seed(2022)
svml.fit2 <- train(diagnosis ~ . , 
                  data = train, 
                  method = "svmLinear2",
                  tuneGrid = data.frame(cost = exp(seq(-5,2,len=50))),
                  trControl = ctrl)

plot(svml.fit2, highlight = TRUE, xTrans = log)
log(svml.fit2$bestTune)
```

```{r eval=FALSE, include=FALSE}
save(svml.fit, file = "./result/model.svml.RData")

load("./result/model.svml.RData")
```

```{r}
svml.fit$bestTune
log(svml.fit$bestTune)

ggplot(svml.fit, highlight = TRUE)

train.pred.prob.svml <- predict(svml.fit, newdata = train)
svml_matrix_train <- confusionMatrix(data = train.pred.prob.svml,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_svml = as.data.frame(1-svml_matrix_train$overall[1])[1,]
train_err_rate_svml

test.pred.prob.svml <- predict(svml.fit, newdata = test)
svml_matrix <- confusionMatrix(data = test.pred.prob.svml,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_svml = as.data.frame(1-svml_matrix$overall[1])[1,]
test_err_rate_svml
```

```{r eval=FALSE, include=FALSE}
save(svml.fit2, file = "./result/model.svml2.RData")

load("./result/model.svml2.RData")
```

```{r}
svml.fit2$bestTune
log(svml.fit2$bestTune)

ggplot(svml2.fit, highlight = TRUE)

train.pred.prob.svml2 <- predict(svml.fit2, newdata = train)
svml2_matrix_train <- confusionMatrix(data = train.pred.prob.svml2,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_svml2 = as.data.frame(1-svml2_matrix_train$overall[1])[1,]
train_err_rate_svml2

test.pred.prob.svml2 <- predict(svml.fit2, newdata = test)
svml2_matrix <- confusionMatrix(data = test.pred.prob.svml2,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_svml2 = as.data.frame(1-svml2_matrix$overall[1])[1,]
test_err_rate_svml2
```

## radial svm
```{r, fig.width=15, fig.height=8}
svmr.grid <- expand.grid(C = exp(seq(-1,4,len=20)),
                         sigma = exp(seq(-6,-2,len=20)))

# tunes over both cost and sigma
set.seed(2022)             
svmr.fit <- train(diagnosis ~ . ,
                  train, 
                  method = "svmRadialSigma",
                  tuneGrid = svmr.grid,
                  trControl = ctrl)

myCol<- rainbow(20)
myPar <- list(superpose.symbol = list(col = myCol),
              superpose.line = list(col = myCol))

plot(svmr.fit, highlight = TRUE, par.settings = myPar)

# tune over cost and uses a single value of sigma based on kernlab's sigest function
set.seed(2022)             
svmr.fit2 <- train(diagnosis ~ . ,
                   train, 
                   method = "svmRadialCost",
                   tuneGrid = data.frame(C = exp(seq(-3,3,len=20))),
                   trControl = ctrl)

# Platt??s probabilistic outputs; use with caution
set.seed(2022)             
svmr.fit3 <- train(diagnosis ~ . ,
                   train, 
                   method = "svmRadialCost",
                   tuneGrid = data.frame(C = exp(seq(-3,3,len=20))),
                   trControl = ctrl,
                   prob.model = TRUE) 
# predict(svmr.fit3, newdata = x_test, type = "prob")

```

```{r eval=FALSE, include=FALSE}
save(svmr.fit, file = "./result/model.svmr.RData")

load("./result/model.svmr.RData")
```

```{r}
svmr.fit$bestTune
log(svmr.fit$bestTune)

ggplot(svmr.fit, highlight = TRUE)

train.pred.prob.svmr <- predict(svmr.fit, newdata = train)
svmr_matrix_train <- confusionMatrix(data = train.pred.prob.svmr,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_svmr = as.data.frame(1-svmr_matrix_train$overall[1])[1,]
train_err_rate_svmr

test.pred.prob.svmr <- predict(svmr.fit, newdata = test)
svmr_matrix <- confusionMatrix(data = test.pred.prob.svmr,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_svmr = as.data.frame(1-svmr_matrix$overall[1])[1,]
test_err_rate_svmr
```

```{r eval=FALSE, include=FALSE}
save(svmr.fit2, file = "./result/model.svmr2.RData")

load("./result/model.svmr2.RData")
```

```{r}
svmr.fit2$bestTune
log(svmr.fit2$bestTune)

ggplot(svml2.fit, highlight = TRUE)

train.pred.prob.svmr2 <- predict(svmr.fit2, newdata = train)
svmr2_matrix_train <- confusionMatrix(data = train.pred.prob.svmr2,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_svmr2 = as.data.frame(1-svmr2_matrix_train$overall[1])[1,]
train_err_rate_svmr2

test.pred.prob.svmr2 <- predict(svmr.fit2, newdata = test)
svmr2_matrix <- confusionMatrix(data = test.pred.prob.svmr2,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_svmr2 = as.data.frame(1-svmr2_matrix$overall[1])[1,]
test_err_rate_svmr2
```

```{r eval=FALSE, include=FALSE}
save(svmr.fit3, file = "./result/model.svmr3.RData")

load("./result/model.svmr3.RData")
```

```{r}
svmr.fit3$bestTune
log(svmr.fit3$bestTune)

ggplot(svml2.fit, highlight = TRUE)

train.pred.prob.svmr3 <- predict(svmr.fit3, newdata = train)
svmr3_matrix_train_train <- confusionMatrix(data = train.pred.prob.svmr3,
                reference = train$diagnosis,
                positive = "pos")

train_err_rate_svmr3 = as.data.frame(1-svmr3_matrix_train_train$overall[1])[1,]
train_err_rate_svmr3

test.pred.prob.svmr3 <- predict(svmr.fit3, newdata = test)
svmr3_matrix <- confusionMatrix(data = test.pred.prob.svmr3,
                reference = test$diagnosis,
                positive = "pos")

test_err_rate_svmr3 = as.data.frame(1-svmr3_matrix$overall[1])[1,]
test_err_rate_svmr3
```

# K means clustering
```{r}
dat <- dat_df
dat$diagnosis[which(dat$diagnosis == 'M')] <- '0'
dat$diagnosis[which(dat$diagnosis == 'B')] <- '1'

train_scl <- scale(train[,1:30])
test_scl <- scale(test[,1:30])
dat_scl <- rbind(train_scl,test_scl)
```

```{r, fig.height=3.5}
fviz_nbclust(dat_scl,
             FUNcluster = kmeans,
             method = "silhouette")
set.seed(2022)
km <- kmeans(dat_scl, centers = 2, nstart = 20)
```

```{r}
km_vis <- fviz_cluster(list(data = dat_scl, cluster = km$cluster), 
                       ellipse.type = "convex", 
                       geom = c("point","text"),
                       labelsize = 5, 
                       palette = "Dark2") + labs(title = "K-means") 

km_vis
```

```{r}
k_cluster_res = as.data.frame(km$cluster) %>%
  mutate(cluster = km$cluster) %>%
  mutate(cluster_2 = cluster - 1)

class_1 = k_cluster_res %>% filter(cluster_2 == 0)
class_2 = k_cluster_res %>% filter(cluster_2 == 1)

id_list1 = rownames(class_1)

dat_cla1 = NULL
dat_cla2 = NULL
i=1
for (i in 1:569) {
  if (dat_df_wait$id[i] %in% id_list1){
    dat_cla1 <- rbind(dat_cla1, dat_df_wait[i,])
  }
  else {
    dat_cla2 <- rbind(dat_cla2, dat_df_wait[i,])
  }
}
i=i+1

c1m <- dim(dat_cla1 %>% filter(diagnosis == "M"))[1]
c1b <- dim(dat_cla1 %>% filter(diagnosis == "B"))[1]
c2m <- dim(dat_cla2 %>% filter(diagnosis == "M"))[1]
c2b <- dim(dat_cla2 %>% filter(diagnosis == "B"))[1]

c1 <- c(c1m,c1b)
c2 <- c(c2m,c2b)
sum <- c(c1m+c1b, c2m+c2b)
c12 <- rbind(c1,c2)
c12 <- cbind(c12,sum)
colnames(c12) <- c("diagnosis = M","diagnosis = B","Total")
rownames(c12) <- c("class 1","class 2")
knitr::kable(as.data.frame(c12))
```

# PCA
```{r, fig.height=3}
mean <- scale(dat[,1:10])
se <- dat[,11:20] %>% scale()
worst <- dat[,21:30] %>% scale()

pca_m <- prcomp(mean)
pca_m$rotation
pca_m$sdev
pca_m$rotation %*% diag(pca_m$sdev)
corrplot(pca_m$rotation %*% diag(pca_m$sdev))
var_m <- get_pca_var(pca_m)
corrplot(var_m$cor)

pca_s <- prcomp(se)
pca_s$rotation
pca_s$sdev
pca_s$rotation %*% diag(pca_s$sdev)
corrplot(pca_s$rotation %*% diag(pca_s$sdev))
var_s <- get_pca_var(pca_s)
corrplot(var_s$cor)

pca_w <- prcomp(worst)
pca_w$rotation
pca_w$sdev
pca_w$rotation %*% diag(pca_w$sdev)
corrplot(pca_w$rotation %*% diag(pca_w$sdev))
var_w <- get_pca_var(pca_w)
corrplot(var_w$cor)
```

```{r, fig.height=4}
fviz_eig(pca_m, addlabels = TRUE)
fviz_eig(pca_s, addlabels = TRUE)
fviz_eig(pca_w, addlabels = TRUE)
```

```{r, fig.height=4}
fviz_pca_biplot(pca_m, axes = c(1,2),
                habillage = ifelse(dat$diagnosis == "1", "M","B"),
                label = c("var_m"),
                addEllipses = TRUE) 

fviz_pca_var(pca_m, col.var = "steelblue", repel = TRUE)
fviz_pca_ind(pca_m,
             habillage = ifelse(dat$diagnosis == "1", "M","B"),
             label = "none",
             addEllipses = TRUE)
```

```{r, fig.height=4}
fviz_pca_biplot(pca_s, axes = c(1,2),
                habillage = ifelse(dat$diagnosis == "1", "M","B"),
                label = c("var_s"),
                addEllipses = TRUE) 

fviz_pca_var(pca_s, col.var = "steelblue", repel = TRUE)
fviz_pca_ind(pca_s,
             habillage = ifelse(dat$diagnosis == "1", "M","B"),
             label = "none",
             addEllipses = TRUE)
```

```{r, fig.height=4}
fviz_pca_biplot(pca_w, axes = c(1,2),
                habillage = ifelse(dat$diagnosis == "1", "M","B"),
                label = c("var_w"),
                addEllipses = TRUE) 

fviz_pca_var(pca_w, col.var = "steelblue", repel = TRUE)
fviz_pca_ind(pca_w,
             habillage = ifelse(dat$diagnosis == "1", "M","B"),
             label = "none",
             addEllipses = TRUE)
```

